name: Typst pdf build

on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: yusancky/setup-typst@v2
      with:
        version: 'v0.7.0'
    - name: Compile memoire pdf
      run: typst compile src/main.typ ./memoire.pdf
    - name: Compile slides pdf
      run: typst compile src/presentation.typ ./presentation.pdf
    - name: Test file presence
      run: file memoire.pdf presentation.pdf
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: memoire
        path: |
          memoire.pdf
          presentation.pdf

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - name: Download pdf
      uses: actions/download-artifact@v3
      with:
        name: memoire
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          memoire.pdf
          presentation.pdf
